# Generated by Django 4.1.7 on 2023-03-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemorder',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(related_name='menus', through='menu.MenuItemOrder', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitemorder',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_order', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitemorder',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
